apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/00-namespace.yaml
  - base/01-configmap.yaml
  - base/02-secret.yaml
  - base/03-init-sql-configmap.yaml
  - base/04-pvcs.yaml
  - deployments/api-gateway.yaml
  - deployments/auth-service.yaml
  - deployments/cart-service.yaml
  - deployments/frontend.yaml
  - deployments/kafka-ui.yaml
  - deployments/kafka.yaml
  - deployments/mysql.yaml
  - deployments/nginx.yaml
  - deployments/order-service.yaml
  - deployments/product-service.yaml
  - deployments/recommendation-service.yaml
  - deployments/redis.yaml
  - services/api-gateway.yaml
  - services/auth-service.yaml
  - services/cart-service.yaml
  - services/frontend.yaml
  - services/kafka-ui.yaml
  - services/kafka.yaml
  - services/mysql.yaml
  - services/nginx.yaml
  - services/order-service.yaml
  - services/product-service.yaml
  - services/recommendation-service.yaml
  - services/redis.yaml
