apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: icecream-hub
spec:
  ports:
    - port: 8081
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: icecream-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          # Image needs to be substituted with real registry path in production
          image: icecream-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: SPRING_DATASOURCE_URL_AUTH
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecream-secret
                  key: MYSQL_PASSWORD
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: JAVA_TOOL_OPTIONS
