apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: icecream-hub
spec:
  ports:
    - port: 8083
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: icecream-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: akhilmylaram/icecream-order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: SPRING_DATASOURCE_URL_ORDER
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icecream-secret
                  key: MYSQL_PASSWORD
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: CART_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: PRODUCT_SERVICE_URL
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: JAVA_TOOL_OPTIONS
