apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: icecream-hub
spec:
  ports:
    - port: 8080
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: icecream-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: akhilmylaram/icecream-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: JAVA_TOOL_OPTIONS
