apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: icecream-hub
spec:
  type: LoadBalancer # Typical for external ingress in simple setups
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: icecream-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: icecream-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
