apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: icecream-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: akhilmylaram/icecream-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: icecream-config
                  key: GATEWAY_URL

