apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Base Setup
  - base/00-namespace.yaml
  - base/01-configmap.yaml
  - base/02-secret.yaml
  - base/03-init-sql-configmap.yaml

  # Databases
  - databases/04-mysql.yaml
  - databases/05-redis.yaml

  # Backend Services
  - backend/06-auth-service.yaml
  - backend/07-product-service.yaml
  - backend/08-cart-service.yaml
  - backend/09-order-service.yaml
  - backend/10-recommendation-service.yaml
  - backend/11-api-gateway.yaml

  # Frontend & Proxy
  - frontend/12-frontend.yaml
  - frontend/13-nginx.yaml
