## IceCream Hub Unified Values

apiGateway:
  image: "akhilmylaram/icecream-gateway"
  tag: "latest"
authService:
  image: "akhilmylaram/icecream-auth"
  tag: "latest"
cartService:
  image: "akhilmylaram/icecream-cart-service"
  tag: "cdaea58455265867ef3baba71b141c23b3c97252"
frontend:
  image: "akhilmylaram/icecream-frontend"
  tag: "7484baf5670c6cd3894d6eb7af6443497b84ccaa"
kafka:
  image: "akhilmylaram/icecream-kafka"
  tag: "latest"
nginx:
  image: "akhilmylaram/icecream-nginx"
  tag: "latest"
orderService:
  image: "akhilmylaram/icecream-order"
  tag: "latest"
productService:
  image: "akhilmylaram/icecream-product"
  tag: "latest"
recommendationService:
  image: "akhilmylaram/icecream-recommendation"
  tag: "latest"
