apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-config
  namespace: icecream-hub
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS auth_db;
    CREATE DATABASE IF NOT EXISTS product_db;
    CREATE DATABASE IF NOT EXISTS order_db;
    CREATE DATABASE IF NOT EXISTS recommendation_db;
    
    GRANT ALL PRIVILEGES ON auth_db.* TO 'icecream_user'@'%';
    GRANT ALL PRIVILEGES ON product_db.* TO 'icecream_user'@'%';
    GRANT ALL PRIVILEGES ON order_db.* TO 'icecream_user'@'%';
    GRANT ALL PRIVILEGES ON recommendation_db.* TO 'icecream_user'@'%';
    FLUSH PRIVILEGES;
